### ISSUE TITLE
For RTU always uses address 1 for slave and setting coils to on/true fails

### ISSUE THREAD

**Issue by milen100** [tbarnhill/modbus#2]
When trying to write to coil 'false" the code generated is correct, but there is no option to send to another slave id - it is always 1!
When trying to set coils to true/ON, the register value is set correctly to 0xFF00 ( 65280 decimal), but some internal check fails for incorrect range:
[function:Func5_WriteCoil] RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -32768 and <= 32767. Received 65280

details:

   throw new ERR_OUT_OF_RANGE('value', `>= ${min} and <= ${max}`, value);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -32768 and <= 32767. Received 65280
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int16BE (internal/buffer.js:787:3)
    at Buffer.writeInt16BE (internal/buffer.js:849:10)
    at makeDataPacket (/home/pi/node_modules/modbus/script.js:192:13)
    at Object.Modbus.rtn.write (/home/pi/node_modules/modbus/script.js:68:20)
    at Object.<anonymous> (/home/pi/test_modbus.js:7:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by tbarnhill** [comment]
Can you please update this using the bug report template

**Comment by milen100** [comment]
I will - if I can find it somewhere😊

**Comment by tbarnhill** [comment]
You have the option to start from a template when you create the issue. 

Here it is copied and pasted 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
