### ISSUE TITLE
should test device.write('c0',true),62580 is out of range

### ISSUE THREAD

**Issue by zengleyi** [tbarnhill/modbus#3]
code:
```
const modbus=require('modbus');
const device = modbus('192.168.199.222',502,1); 
(async()=>{
//Read
let myCoil = await device.read('c0')
let myHoldingRegister = await device.read('hr0') 
let myHoldingRegisters = await device.read('hr1-2') 

//Write
await device.write('c0',true)
await device.write('hr0',15)
})();
```
terminal:
```
tx: 0002000000060101ffff0001
rx: 000200000003018102
tx: 0003000000060103ffff0001
rx: 000300000003018302
tx: 000400000006010300000002
rx: 00040000000701030400000000
(node:1746) UnhandledPromiseRejectionWarning: RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -32768 and <= 32767. Received 65280
    at checkInt (internal/buffer.js:63:11)
    at writeU_Int16BE (internal/buffer.js:823:3)
    at Buffer.writeInt16BE (internal/buffer.js:885:10)
    at makeDataPacket (/home/zly/projects/test/node_modules/modbus/script.js:192:13)
    at Object.Modbus.rtn.write (/home/zly/projects/test/node_modules/modbus/script.js:68:20)
    at /home/zly/projects/test/test.js:10:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1746) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1746) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tbarnhill** [comment]
Are you sure your byte offset is correct? This can vary depending on the manufacturer of the modbus device your talking to. 
Try:
`device.write('c1',true)`

**Comment by tbarnhill** [comment]
The issue might be on line 66 of the script.js file.
 ` if (funcCode==5&&value==true){value = 65280} // To force a coil on you send FF00 not 0001`

Does deleting this line correct your issue?

**Comment by zengleyi** [comment]
> The issue might be on line 66 of the script.js file. ` if (funcCode==5&&value==true){value = 65280} // To force a coil on you send FF00 not 0001`
> 
> Does deleting this line correct your issue?

Delete this line and the coil will not be able to respond.

Facts have proved that close the coil does need to send 0xff00 bytecode, so here it is necessary to judge whether the value is greater than 2-bit hexadecimal to split, and divide the value into 0xff and 0x00.

In addition, not only writing the coil, but also assigning 0xff00 to a holding register will lead to the same error.

**Comment by Aaqu** [comment]
this work for me (tested only on coil)
```
if (funcCode === 5 || funcCode === 6) {
  buf.writeUInt16BE(data, 10);
}
```
